from pathlib import Path
v=Path('/Users/Artem/.zenflow/worktrees/documentation-vault');t=v/'tasks/new-task-be0b';sha='f9031c96afa3cd82525f33084986bee169be7e49'
def replace(p,a,b):
 s=p.read_text();assert s.count(a)==1,(p,a[:90]);p.write_text(s.replace(a,b))
p=t/'ios-project-work-system-plan.md'
replace(p,'| [ ] W5.3.b | Final diff/commit/remote receipt | Quality gates and current identities/permissions, no unresolved owned candidate P0–P2, exact remote SHA |','| [x] W5.3.b | Final diff/commit/remote receipt | E11 exact range e132655..f9031c96 reviewed, committed/pushed; independent remote SHA and remote-state PASS. Later closure commit has a separate exact receipt; no self-SHA assertion |')
replace(p,'Current W5 review packet (not an acceptance or release grant):','Current W5 scoped verification verdict (evidence, not a permission or release grant):')
replace(p,'resume; no deletion now and no foreign cleanup. W5.3.b publication gate remains open in this candidate until its actual exact-HEAD/remote receipt; core evidence is now complete. No pre-push completion claim. A separate compact closure records the first confirmed publication; any later commit requires its own exact review/receipt.','resume; no deletion now and no foreign cleanup. W5.3.b CLOSED for actual E11 publication: exact reviewed e132655..f9031c96 range, clean canonical, independent remote f9031c96 confirmation and active remote-state PASS. This closure records that prior confirmed event; its own later commit requires a new exact review/remote receipt before completion reporting. Required W1–W5 named core work complete; general Library/improvement and specialist acceptance remain separate OPEN.')
replace(p,'Next: exact publication gate, then a concrete human decision about genuine new work for LIB-004; no repeat of known cases.','E11 exact publication gate completed; next concrete human decision about genuine new work for LIB-004, no repeat of known cases.')
p.write_text(p.read_text()+'\nPublication closeout: E11 remote '+sha+' independently confirmed; current local recovery and external publication receipt retain full exact range/checks. W5.3.b closes the actual published named-core packet, not LIB-004/general release. Further closure publication gated separately.\n')
for name in ['plan.md','handoff.md']:
 p=t/name;s=p.read_text()
 s=s.replace('W4 required named core cases complete, W5 publication/Library gate OPEN','W4/W5 required named core work complete; general Library gate OPEN')
 s=s.replace('Final publication gate and LIB-004 P2 OPEN independently.','E11 publication verified at f9031c96; LIB-004 P2 OPEN independently.')
 s=s.replace('- [ ] W5.3.b exact final publication/remote receipt; candidate alone does not close it.','- [x] W5.3.b exact E11 publication e132655..f9031c96, committed/pushed and independent remote/remote-state PASS; closure commit separately gated.')
 s=s.replace('Next: finish exact canonical publication/remote gates; then human selects a genuine new\nproject task for Library utility evidence.','E11 canonical publication f9031c96 independently confirmed; remote-state PASS.\nNext human decision: select genuine new project work for Library utility evidence.')
 p.write_text(s)
p=v/'apps/BattleshipGame/PROJECT_CONTEXT.md';replace(p,'Next safe system action: finish E11 publication, then select genuine new task for Library utility evidence; current BG/TC mode receipts below, no app backlog.','Next safe system action: select genuine new task for Library utility evidence after confirmed E11 publication f9031c96; current BG/TC mode receipts below, no app backlog.')
p=t/'ios-project-work-system-ordered-startup-check.md';replace(p,'Canonical publication gate remains pending until actual reviewed HEAD/remote confirmation; document existence alone grants nothing.','E11 publication subsequently completed: exact reviewed e132655..f9031c96 range, independent remote main '+sha+' and active remote-state PASS. This closure records the confirmed prior publication; any later commit needs its own exact review/remote receipt. Document existence alone grants nothing.')
print('W5.3.b closed from actual independently confirmed prior E11 publication;5 owned canonical files.')
